### ISSUE TITLE
关于鼠标移到屏幕左侧，导航栏跳回的问题

### ISSUE THREAD

**Issue by lasagnasu1** [DND5eChm/5echm_web#2]
#### 描述
在浏览器中，使用鼠标，将指针移动到屏幕左侧后，导航栏的滚动条将复位到顶端，有些一点妨碍导航窗口的使用使用。
经查在`webhelpcontents.htm`文件中第233行至240行发现了如下函数：
```
function body_onmousemove(event){
if(typeof(document.body.scrollTop)!='undefined'){
if(parseInt(event.clientX)<5){
window.scroll(0,document.body.scrollTop);}}
if(typeof(window.scrollY)!='undefined'){
if(parseInt(event.clientX)<5){
window.scrollTo(0,window.scrollY);}}
}
```
将这个函数的内容注释后似乎不影响网页的运行，请问这个“滚动条将复位到顶端”这是某种特别设计的特征吗？如果不是，请问能否将其删除掉。

**Comment by kagangtuya-star** [comment]
已尝试注释
https://github.com/DND5eChm/5echm_web/commit/4729beb77a96fa8f1bc027a9400be082a5f16ca5
